services:
  - type: web
    name: mockmate-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: "5000"
      - key: MONGO_URI
        value: "mongodb+srv://Soham:Soham2005@cluster0.6ewppht.mongodb.net/?appName=Cluster0"
      - key: GEMINI_API_KEY
        value: "AIzaSyDPM4WxEVgxgfviIgp5s8smMxUslBH8u9g"
      - key: JWT_SECRET
        generateValue: true
